name: Install MATLAB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      s3:
        image: localstack/localstack:4.2
        ports:
          - 4566:4566
        options: >-
          --name localstack
          -e SERVICES=s3
          -e DEFAULT_REGION=us-east-1
        volumes:
          - "./testfiles:/tmp/localstack/data"
          - "./aws:/docker-entrypoint-initaws.d"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check file availability
      env:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: us-east-1
        S3_ENDPOINT: http://localhost:4566
      run: |
        # Example: List files in the mounted directory
        ls /tmp/localstack/data