name: Test with LocalStack

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566  # LocalStack's edge port for all services
        options: >-
          --name localstack
          -e SERVICES=s3
          -e DEFAULT_REGION=us-east-1
        volumes:
          - ${{github.workspace}}/testfiles:/tmp/localstack/data
          - ${{github.workspace}}/aws:/docker-entrypoint-initaws.d

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install curl
      run: sudo apt-get install -y curl

    - name: Run tests
      env:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        S3_ENDPOINT: http://localhost:4566
      run: |
        # Create a bucket using the AWS S3 REST API
        BUCKET_NAME=my-test-bucket
        curl -X PUT "${S3_ENDPOINT}/${BUCKET_NAME}"

        # List buckets to verify creation
        echo "Listing buckets:"
        curl "${S3_ENDPOINT}"