name: Test with LocalStack and Boto3

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Start LocalStack
      uses: localstack/actions@v1
      with:
        services: s3
        wait: true

    - name: Prepare data directory
      run: mkdir -p data && echo "Sample data" > data/sample.txt

    - name: Run Python script
      env:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: us-east-1
        S3_ENDPOINT: http://localhost:4566
      run: python s3_operations.py