name: Test with LocalStack and Boto3

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566  # LocalStack's edge port for all services
        options: >-
          --name localstack
          -e SERVICES=s3
          -e DEFAULT_REGION=us-east-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024a

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Run Python script
      env:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: us-east-1
        S3_ENDPOINT: http://localhost:4566
      run: python create_bucket.py

    - name: Run tests
      uses: matlab-actions/run-tests@v2
      with:
        select-by-folder: 'test'
        code-coverage-cobertura: cobertura.xml

    - name: Upload codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: cobertura.xml