name: Test with LocalStack

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566  # LocalStack's edge port for all services
        options: >-
          --name localstack
          -e SERVICES=s3
          -e DEFAULT_REGION=us-east-1
          -v "${{github.workspace}}/test/testfiles:/data"
          -v "${{github.workspace}}/aws:/docker-entrypoint-initaws.d"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        clean: false

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: R2024a

    - name: Run tests
      uses: matlab-actions/run-tests@v2
      with:
        select-by-folder: 'test'
        output-detail: 'verbose'