name: Test with LocalStack

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566  # LocalStack's edge port for all services
        options: >-
          --name localstack
          -e SERVICES=s3
          -e DEFAULT_REGION=us-east-1
        volumes:
          - ${{github.workspace}}/testfiles:/mnt/data
          - ${{github.workspace}}/aws:/docker-entrypoint-initaws.d

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli-local

    - name: Run tests
      run: |
        echo "List buckets:"
        awslocal s3 ls