name: Test with LocalStack and Boto3

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Start LocalStack
      uses: localstack/actions@v1
      with:
        services: s3
        wait: true

    - name: Prepare data directory
      run: mkdir -p data && echo "Sample data" > data/sample.txt

    - name: Run tests
      env:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: us-east-1
        S3_ENDPOINT: http://localhost:4566
      run: |
        # Python script to interact with LocalStack S3 using Boto3
        echo "import boto3
import os

def main():
    s3 = boto3.client(
        's3',
        endpoint_url=os.getenv('S3_ENDPOINT'),
        aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
        aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
        region_name=os.getenv('AWS_DEFAULT_REGION')
    )

    # Create a bucket
    bucket_name = 'my-test-bucket'
    s3.create_bucket(Bucket=bucket_name)

    # List buckets to verify creation
    response = s3.list_buckets()
    print('Buckets:', [bucket['Name'] for bucket in response['Buckets']])

    # Upload a file to the bucket
    s3.upload_file('data/sample.txt', bucket_name, 'sample.txt')

    # List objects in the bucket
    response = s3.list_objects_v2(Bucket=bucket_name)
    print('Objects in bucket:', [obj['Key'] for obj in response.get('Contents', [])])

if __name__ == '__main__':
    main()" > test_script.py

        # Run the Python script
        python test_script.py